# Generated by Django 5.2.6 on 2025-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                through="carts.CartProduct", to="products.product"
            ),
        ),
    ]
