# Generated by Django 5.2.6 on 2025-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
