# Generated by Django 5.2.6 on 2025-11-07 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DirEnvio", "0001_initial"),
        ("orden", "0002_orden_ordenid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="direccion_envio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DirEnvio.direccionenvio",
            ),
        ),
    ]
