# Generated by Django 5.2.6 on 2025-12-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DirEnvio", "0001_initial"),
        ("orden", "0003_orden_direccion_envio"),
        ("products", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="direccion_envio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="DirEnvio.direccionenvio",
            ),
        ),
        migrations.CreateModel(
            name="OrdenProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orden.orden",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
