# Generated by Django 5.2.6 on 2025-12-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orden", "0004_alter_orden_direccion_envio_ordenproducto"),
        ("promo_codigo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="promo_codigo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="promo_codigo.promocodigo",
            ),
        ),
    ]
